project:
  type: website
  output-dir: docs
  
publish:
  gh-pages: true
  


website:
  favicon: logo_favicon.png
  navbar:
    logo: logo.png
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - app_features.qmd
      - evidence&analytics.qmd
      - research&publications.qmd
      - contact.qmd
      
  
       

format:
  html:
    theme: zephyr
    css: styles.css
    toc: false

editor: visual




